/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels'
import { Route as AuthenticatedGoalsGoalIdRouteImport } from './routes/_authenticated/goals.$goalId'
import { Route as AuthenticatedOrganizationsNewRouteImport } from './routes/_authenticated/organizations/new'
import { Route as AuthenticatedSettingsApiTokensRouteImport } from './routes/_authenticated/settings/api-tokens'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsMcpServerRouteImport } from './routes/_authenticated/settings/mcp-server'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSettingsPersonalRouteImport } from './routes/_authenticated/settings/personal'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsGoalIdRoute =
  AuthenticatedGoalsGoalIdRouteImport.update({
    id: '/$goalId',
    path: '/$goalId',
    getParentRoute: () => AuthenticatedGoalsRoute,
  } as any)
const AuthenticatedOrganizationsNewRoute =
  AuthenticatedOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsApiTokensRoute =
  AuthenticatedSettingsApiTokensRouteImport.update({
    id: '/settings/api-tokens',
    path: '/settings/api-tokens',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMcpServerRoute =
  AuthenticatedSettingsMcpServerRouteImport.update({
    id: '/settings/mcp-server',
    path: '/settings/mcp-server',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPersonalRoute =
  AuthenticatedSettingsPersonalRouteImport.update({
    id: '/settings/personal',
    path: '/settings/personal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AuthenticatedAccountRoute
  '/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/organizations/new': typeof AuthenticatedOrganizationsNewRoute
  '/settings/api-tokens': typeof AuthenticatedSettingsApiTokensRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/mcp-server': typeof AuthenticatedSettingsMcpServerRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/personal': typeof AuthenticatedSettingsPersonalRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AuthenticatedAccountRoute
  '/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/organizations/new': typeof AuthenticatedOrganizationsNewRoute
  '/settings/api-tokens': typeof AuthenticatedSettingsApiTokensRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/mcp-server': typeof AuthenticatedSettingsMcpServerRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/personal': typeof AuthenticatedSettingsPersonalRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute
  '/_authenticated/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/_authenticated/organizations/new': typeof AuthenticatedOrganizationsNewRoute
  '/_authenticated/settings/api-tokens': typeof AuthenticatedSettingsApiTokensRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/mcp-server': typeof AuthenticatedSettingsMcpServerRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/settings/personal': typeof AuthenticatedSettingsPersonalRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/verify-email'
    | '/account'
    | '/goals'
    | '/home'
    | '/labels'
    | '/goals/$goalId'
    | '/organizations/new'
    | '/settings/api-tokens'
    | '/settings/appearance'
    | '/settings/mcp-server'
    | '/settings/organization'
    | '/settings/personal'
    | '/settings/profile'
    | '/settings/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/verify-email'
    | '/account'
    | '/goals'
    | '/home'
    | '/labels'
    | '/goals/$goalId'
    | '/organizations/new'
    | '/settings/api-tokens'
    | '/settings/appearance'
    | '/settings/mcp-server'
    | '/settings/organization'
    | '/settings/personal'
    | '/settings/profile'
    | '/settings/team'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/verify-email'
    | '/_authenticated/account'
    | '/_authenticated/goals'
    | '/_authenticated/home'
    | '/_authenticated/labels'
    | '/_authenticated/goals/$goalId'
    | '/_authenticated/organizations/new'
    | '/_authenticated/settings/api-tokens'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/mcp-server'
    | '/_authenticated/settings/organization'
    | '/_authenticated/settings/personal'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals/$goalId': {
      id: '/_authenticated/goals/$goalId'
      path: '/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AuthenticatedGoalsGoalIdRouteImport
      parentRoute: typeof AuthenticatedGoalsRoute
    }
    '/_authenticated/organizations/new': {
      id: '/_authenticated/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof AuthenticatedOrganizationsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/api-tokens': {
      id: '/_authenticated/settings/api-tokens'
      path: '/settings/api-tokens'
      fullPath: '/settings/api-tokens'
      preLoaderRoute: typeof AuthenticatedSettingsApiTokensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/mcp-server': {
      id: '/_authenticated/settings/mcp-server'
      path: '/settings/mcp-server'
      fullPath: '/settings/mcp-server'
      preLoaderRoute: typeof AuthenticatedSettingsMcpServerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/personal': {
      id: '/_authenticated/settings/personal'
      path: '/settings/personal'
      fullPath: '/settings/personal'
      preLoaderRoute: typeof AuthenticatedSettingsPersonalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedGoalsRouteChildren {
  AuthenticatedGoalsGoalIdRoute: typeof AuthenticatedGoalsGoalIdRoute
}

const AuthenticatedGoalsRouteChildren: AuthenticatedGoalsRouteChildren = {
  AuthenticatedGoalsGoalIdRoute: AuthenticatedGoalsGoalIdRoute,
}

const AuthenticatedGoalsRouteWithChildren =
  AuthenticatedGoalsRoute._addFileChildren(AuthenticatedGoalsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute
  AuthenticatedOrganizationsNewRoute: typeof AuthenticatedOrganizationsNewRoute
  AuthenticatedSettingsApiTokensRoute: typeof AuthenticatedSettingsApiTokensRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsMcpServerRoute: typeof AuthenticatedSettingsMcpServerRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSettingsPersonalRoute: typeof AuthenticatedSettingsPersonalRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedOrganizationsNewRoute: AuthenticatedOrganizationsNewRoute,
  AuthenticatedSettingsApiTokensRoute: AuthenticatedSettingsApiTokensRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsMcpServerRoute: AuthenticatedSettingsMcpServerRoute,
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
  AuthenticatedSettingsPersonalRoute: AuthenticatedSettingsPersonalRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
