import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

type OpenApiDocument = {
  info: {
    title: string;
    description: string;
  };
};

const docsRoot = resolve(import.meta.dir, "..");
const repositoryRoot = resolve(docsRoot, "../..");
const generatedSpecDir = resolve(docsRoot, "generated/openapi");
const contentDir = resolve(docsRoot, "content/docs/api");

const services = [
  {
    slug: "rest-api",
    source: resolve(repositoryRoot, "services/api/openapi.json")
  }
];

await mkdir(generatedSpecDir, { recursive: true });
await mkdir(contentDir, { recursive: true });

for (const service of services) {
  const document = (await Bun.file(service.source).json()) as OpenApiDocument;
  const specFilename = `${service.slug}.json`;
  const specOutput = resolve(generatedSpecDir, specFilename);
  const pageOutput = resolve(contentDir, `${service.slug}.mdx`);

  await writeFile(specOutput, `${JSON.stringify(document, null, 2)}\n`);
  await writeFile(
    pageOutput,
    `---\ntitle: ${JSON.stringify(document.info.title)}\ndescription: ${JSON.stringify(document.info.description)}\n---\n\n{/* Generated by bun run docs:generate. Do not edit directly. */}\n\nimport spec from "../../../generated/openapi/${specFilename}";\nimport { OpenApiReference } from "../../../components/openapi-reference";\n\n<OpenApiReference spec={spec} />\n`
  );

  console.log(`Generated API docs for ${document.info.title}`);
}

await writeFile(
  resolve(contentDir, "meta.json"),
  `${JSON.stringify(
    { title: "API Reference", pages: services.map((service) => service.slug) },
    null,
    2
  )}\n`
);
